// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package vpc_endpoint

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.DomainARN, b.ko.Spec.DomainARN) {
		delta.Add("Spec.DomainARN", a.ko.Spec.DomainARN, b.ko.Spec.DomainARN)
	} else if a.ko.Spec.DomainARN != nil && b.ko.Spec.DomainARN != nil {
		if *a.ko.Spec.DomainARN != *b.ko.Spec.DomainARN {
			delta.Add("Spec.DomainARN", a.ko.Spec.DomainARN, b.ko.Spec.DomainARN)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.DomainRef, b.ko.Spec.DomainRef) {
		delta.Add("Spec.DomainRef", a.ko.Spec.DomainRef, b.ko.Spec.DomainRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.VPCOptions, b.ko.Spec.VPCOptions) {
		delta.Add("Spec.VPCOptions", a.ko.Spec.VPCOptions, b.ko.Spec.VPCOptions)
	} else if a.ko.Spec.VPCOptions != nil && b.ko.Spec.VPCOptions != nil {
		if len(a.ko.Spec.VPCOptions.SecurityGroupIDs) != len(b.ko.Spec.VPCOptions.SecurityGroupIDs) {
			delta.Add("Spec.VPCOptions.SecurityGroupIDs", a.ko.Spec.VPCOptions.SecurityGroupIDs, b.ko.Spec.VPCOptions.SecurityGroupIDs)
		} else if len(a.ko.Spec.VPCOptions.SecurityGroupIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.VPCOptions.SecurityGroupIDs, b.ko.Spec.VPCOptions.SecurityGroupIDs) {
				delta.Add("Spec.VPCOptions.SecurityGroupIDs", a.ko.Spec.VPCOptions.SecurityGroupIDs, b.ko.Spec.VPCOptions.SecurityGroupIDs)
			}
		}
		if len(a.ko.Spec.VPCOptions.SubnetIDs) != len(b.ko.Spec.VPCOptions.SubnetIDs) {
			delta.Add("Spec.VPCOptions.SubnetIDs", a.ko.Spec.VPCOptions.SubnetIDs, b.ko.Spec.VPCOptions.SubnetIDs)
		} else if len(a.ko.Spec.VPCOptions.SubnetIDs) > 0 {
			if !ackcompare.SliceStringPEqual(a.ko.Spec.VPCOptions.SubnetIDs, b.ko.Spec.VPCOptions.SubnetIDs) {
				delta.Add("Spec.VPCOptions.SubnetIDs", a.ko.Spec.VPCOptions.SubnetIDs, b.ko.Spec.VPCOptions.SubnetIDs)
			}
		}
	}

	return delta
}
