// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package domain

import (
	"context"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/opensearchservice"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/opensearchservice-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.OpenSearchService{}
	_ = &svcapitypes.Domain{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer exit(err)
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadOneInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newDescribeRequestPayload(r)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.DescribeDomainOutput
	resp, err = rm.sdkapi.DescribeDomainWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_ONE", "DescribeDomain", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "ResourceNotFoundException" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.DomainStatus.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.DomainStatus.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.DomainStatus.AccessPolicies != nil {
		ko.Spec.AccessPolicies = resp.DomainStatus.AccessPolicies
	} else {
		ko.Spec.AccessPolicies = nil
	}
	if resp.DomainStatus.AdvancedOptions != nil {
		f2 := map[string]*string{}
		for f2key, f2valiter := range resp.DomainStatus.AdvancedOptions {
			var f2val string
			f2val = *f2valiter
			f2[f2key] = &f2val
		}
		ko.Spec.AdvancedOptions = f2
	} else {
		ko.Spec.AdvancedOptions = nil
	}
	if resp.DomainStatus.AdvancedSecurityOptions != nil {
		f3 := &svcapitypes.AdvancedSecurityOptionsInput{}
		if resp.DomainStatus.AdvancedSecurityOptions.Enabled != nil {
			f3.Enabled = resp.DomainStatus.AdvancedSecurityOptions.Enabled
		}
		if resp.DomainStatus.AdvancedSecurityOptions.InternalUserDatabaseEnabled != nil {
			f3.InternalUserDatabaseEnabled = resp.DomainStatus.AdvancedSecurityOptions.InternalUserDatabaseEnabled
		}
		if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions != nil {
			f3f2 := &svcapitypes.SAMLOptionsInput{}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Enabled != nil {
				f3f2.Enabled = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Enabled
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp != nil {
				f3f2f1 := &svcapitypes.SAMLIDp{}
				if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.EntityId != nil {
					f3f2f1.EntityID = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.EntityId
				}
				if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.MetadataContent != nil {
					f3f2f1.MetadataContent = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.MetadataContent
				}
				f3f2.IDp = f3f2f1
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.RolesKey != nil {
				f3f2.RolesKey = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.RolesKey
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes != nil {
				f3f2.SessionTimeoutMinutes = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SubjectKey != nil {
				f3f2.SubjectKey = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SubjectKey
			}
			f3.SAMLOptions = f3f2
		}
		ko.Spec.AdvancedSecurityOptions = f3
	} else {
		ko.Spec.AdvancedSecurityOptions = nil
	}
	if resp.DomainStatus.AutoTuneOptions != nil {
		f4 := &svcapitypes.AutoTuneOptionsInput{}
		ko.Spec.AutoTuneOptions = f4
	} else {
		ko.Spec.AutoTuneOptions = nil
	}
	if resp.DomainStatus.ClusterConfig != nil {
		f5 := &svcapitypes.ClusterConfig{}
		if resp.DomainStatus.ClusterConfig.ColdStorageOptions != nil {
			f5f0 := &svcapitypes.ColdStorageOptions{}
			if resp.DomainStatus.ClusterConfig.ColdStorageOptions.Enabled != nil {
				f5f0.Enabled = resp.DomainStatus.ClusterConfig.ColdStorageOptions.Enabled
			}
			f5.ColdStorageOptions = f5f0
		}
		if resp.DomainStatus.ClusterConfig.DedicatedMasterCount != nil {
			f5.DedicatedMasterCount = resp.DomainStatus.ClusterConfig.DedicatedMasterCount
		}
		if resp.DomainStatus.ClusterConfig.DedicatedMasterEnabled != nil {
			f5.DedicatedMasterEnabled = resp.DomainStatus.ClusterConfig.DedicatedMasterEnabled
		}
		if resp.DomainStatus.ClusterConfig.DedicatedMasterType != nil {
			f5.DedicatedMasterType = resp.DomainStatus.ClusterConfig.DedicatedMasterType
		}
		if resp.DomainStatus.ClusterConfig.InstanceCount != nil {
			f5.InstanceCount = resp.DomainStatus.ClusterConfig.InstanceCount
		}
		if resp.DomainStatus.ClusterConfig.InstanceType != nil {
			f5.InstanceType = resp.DomainStatus.ClusterConfig.InstanceType
		}
		if resp.DomainStatus.ClusterConfig.WarmCount != nil {
			f5.WarmCount = resp.DomainStatus.ClusterConfig.WarmCount
		}
		if resp.DomainStatus.ClusterConfig.WarmEnabled != nil {
			f5.WarmEnabled = resp.DomainStatus.ClusterConfig.WarmEnabled
		}
		if resp.DomainStatus.ClusterConfig.WarmType != nil {
			f5.WarmType = resp.DomainStatus.ClusterConfig.WarmType
		}
		if resp.DomainStatus.ClusterConfig.ZoneAwarenessConfig != nil {
			f5f9 := &svcapitypes.ZoneAwarenessConfig{}
			if resp.DomainStatus.ClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount != nil {
				f5f9.AvailabilityZoneCount = resp.DomainStatus.ClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount
			}
			f5.ZoneAwarenessConfig = f5f9
		}
		if resp.DomainStatus.ClusterConfig.ZoneAwarenessEnabled != nil {
			f5.ZoneAwarenessEnabled = resp.DomainStatus.ClusterConfig.ZoneAwarenessEnabled
		}
		ko.Spec.ClusterConfig = f5
	} else {
		ko.Spec.ClusterConfig = nil
	}
	if resp.DomainStatus.CognitoOptions != nil {
		f6 := &svcapitypes.CognitoOptions{}
		if resp.DomainStatus.CognitoOptions.Enabled != nil {
			f6.Enabled = resp.DomainStatus.CognitoOptions.Enabled
		}
		if resp.DomainStatus.CognitoOptions.IdentityPoolId != nil {
			f6.IdentityPoolID = resp.DomainStatus.CognitoOptions.IdentityPoolId
		}
		if resp.DomainStatus.CognitoOptions.RoleArn != nil {
			f6.RoleARN = resp.DomainStatus.CognitoOptions.RoleArn
		}
		if resp.DomainStatus.CognitoOptions.UserPoolId != nil {
			f6.UserPoolID = resp.DomainStatus.CognitoOptions.UserPoolId
		}
		ko.Spec.CognitoOptions = f6
	} else {
		ko.Spec.CognitoOptions = nil
	}
	if resp.DomainStatus.Created != nil {
		ko.Status.Created = resp.DomainStatus.Created
	} else {
		ko.Status.Created = nil
	}
	if resp.DomainStatus.Deleted != nil {
		ko.Status.Deleted = resp.DomainStatus.Deleted
	} else {
		ko.Status.Deleted = nil
	}
	if resp.DomainStatus.DomainEndpointOptions != nil {
		f9 := &svcapitypes.DomainEndpointOptions{}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpoint != nil {
			f9.CustomEndpoint = resp.DomainStatus.DomainEndpointOptions.CustomEndpoint
		}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpointCertificateArn != nil {
			f9.CustomEndpointCertificateARN = resp.DomainStatus.DomainEndpointOptions.CustomEndpointCertificateArn
		}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpointEnabled != nil {
			f9.CustomEndpointEnabled = resp.DomainStatus.DomainEndpointOptions.CustomEndpointEnabled
		}
		if resp.DomainStatus.DomainEndpointOptions.EnforceHTTPS != nil {
			f9.EnforceHTTPS = resp.DomainStatus.DomainEndpointOptions.EnforceHTTPS
		}
		if resp.DomainStatus.DomainEndpointOptions.TLSSecurityPolicy != nil {
			f9.TLSSecurityPolicy = resp.DomainStatus.DomainEndpointOptions.TLSSecurityPolicy
		}
		ko.Spec.DomainEndpointOptions = f9
	} else {
		ko.Spec.DomainEndpointOptions = nil
	}
	if resp.DomainStatus.DomainId != nil {
		ko.Status.DomainID = resp.DomainStatus.DomainId
	} else {
		ko.Status.DomainID = nil
	}
	if resp.DomainStatus.DomainName != nil {
		ko.Spec.Name = resp.DomainStatus.DomainName
	} else {
		ko.Spec.Name = nil
	}
	if resp.DomainStatus.EBSOptions != nil {
		f12 := &svcapitypes.EBSOptions{}
		if resp.DomainStatus.EBSOptions.EBSEnabled != nil {
			f12.EBSEnabled = resp.DomainStatus.EBSOptions.EBSEnabled
		}
		if resp.DomainStatus.EBSOptions.Iops != nil {
			f12.IOPS = resp.DomainStatus.EBSOptions.Iops
		}
		if resp.DomainStatus.EBSOptions.VolumeSize != nil {
			f12.VolumeSize = resp.DomainStatus.EBSOptions.VolumeSize
		}
		if resp.DomainStatus.EBSOptions.VolumeType != nil {
			f12.VolumeType = resp.DomainStatus.EBSOptions.VolumeType
		}
		ko.Spec.EBSOptions = f12
	} else {
		ko.Spec.EBSOptions = nil
	}
	if resp.DomainStatus.EncryptionAtRestOptions != nil {
		f13 := &svcapitypes.EncryptionAtRestOptions{}
		if resp.DomainStatus.EncryptionAtRestOptions.Enabled != nil {
			f13.Enabled = resp.DomainStatus.EncryptionAtRestOptions.Enabled
		}
		if resp.DomainStatus.EncryptionAtRestOptions.KmsKeyId != nil {
			f13.KMSKeyID = resp.DomainStatus.EncryptionAtRestOptions.KmsKeyId
		}
		ko.Spec.EncryptionAtRestOptions = f13
	} else {
		ko.Spec.EncryptionAtRestOptions = nil
	}
	if resp.DomainStatus.Endpoint != nil {
		ko.Status.Endpoint = resp.DomainStatus.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.DomainStatus.Endpoints != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.DomainStatus.Endpoints {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Status.Endpoints = f15
	} else {
		ko.Status.Endpoints = nil
	}
	if resp.DomainStatus.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.DomainStatus.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.DomainStatus.LogPublishingOptions != nil {
		f17 := map[string]*svcapitypes.LogPublishingOption{}
		for f17key, f17valiter := range resp.DomainStatus.LogPublishingOptions {
			f17val := &svcapitypes.LogPublishingOption{}
			if f17valiter.CloudWatchLogsLogGroupArn != nil {
				f17val.CloudWatchLogsLogGroupARN = f17valiter.CloudWatchLogsLogGroupArn
			}
			if f17valiter.Enabled != nil {
				f17val.Enabled = f17valiter.Enabled
			}
			f17[f17key] = f17val
		}
		ko.Spec.LogPublishingOptions = f17
	} else {
		ko.Spec.LogPublishingOptions = nil
	}
	if resp.DomainStatus.NodeToNodeEncryptionOptions != nil {
		f18 := &svcapitypes.NodeToNodeEncryptionOptions{}
		if resp.DomainStatus.NodeToNodeEncryptionOptions.Enabled != nil {
			f18.Enabled = resp.DomainStatus.NodeToNodeEncryptionOptions.Enabled
		}
		ko.Spec.NodeToNodeEncryptionOptions = f18
	} else {
		ko.Spec.NodeToNodeEncryptionOptions = nil
	}
	if resp.DomainStatus.Processing != nil {
		ko.Status.Processing = resp.DomainStatus.Processing
	} else {
		ko.Status.Processing = nil
	}
	if resp.DomainStatus.ServiceSoftwareOptions != nil {
		f20 := &svcapitypes.ServiceSoftwareOptions{}
		if resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate != nil {
			f20.AutomatedUpdateDate = &metav1.Time{*resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate}
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Cancellable != nil {
			f20.Cancellable = resp.DomainStatus.ServiceSoftwareOptions.Cancellable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion != nil {
			f20.CurrentVersion = resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Description != nil {
			f20.Description = resp.DomainStatus.ServiceSoftwareOptions.Description
		}
		if resp.DomainStatus.ServiceSoftwareOptions.NewVersion != nil {
			f20.NewVersion = resp.DomainStatus.ServiceSoftwareOptions.NewVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment != nil {
			f20.OptionalDeployment = resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable != nil {
			f20.UpdateAvailable = resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus != nil {
			f20.UpdateStatus = resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus
		}
		ko.Status.ServiceSoftwareOptions = f20
	} else {
		ko.Status.ServiceSoftwareOptions = nil
	}
	if resp.DomainStatus.SnapshotOptions != nil {
		f21 := &svcapitypes.SnapshotOptions{}
		if resp.DomainStatus.SnapshotOptions.AutomatedSnapshotStartHour != nil {
			f21.AutomatedSnapshotStartHour = resp.DomainStatus.SnapshotOptions.AutomatedSnapshotStartHour
		}
		ko.Status.SnapshotOptions = f21
	} else {
		ko.Status.SnapshotOptions = nil
	}
	if resp.DomainStatus.UpgradeProcessing != nil {
		ko.Status.UpgradeProcessing = resp.DomainStatus.UpgradeProcessing
	} else {
		ko.Status.UpgradeProcessing = nil
	}
	if resp.DomainStatus.VPCOptions != nil {
		f23 := &svcapitypes.VPCOptions{}
		if resp.DomainStatus.VPCOptions.SecurityGroupIds != nil {
			f23f1 := []*string{}
			for _, f23f1iter := range resp.DomainStatus.VPCOptions.SecurityGroupIds {
				var f23f1elem string
				f23f1elem = *f23f1iter
				f23f1 = append(f23f1, &f23f1elem)
			}
			f23.SecurityGroupIDs = f23f1
		}
		if resp.DomainStatus.VPCOptions.SubnetIds != nil {
			f23f2 := []*string{}
			for _, f23f2iter := range resp.DomainStatus.VPCOptions.SubnetIds {
				var f23f2elem string
				f23f2elem = *f23f2iter
				f23f2 = append(f23f2, &f23f2elem)
			}
			f23.SubnetIDs = f23f2
		}
		ko.Spec.VPCOptions = f23
	} else {
		ko.Spec.VPCOptions = nil
	}

	rm.setStatusDefaults(ko)
	if domainProcessing(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
	} else {
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionTrue, nil, nil)
	}

	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadOneInput returns true if there are any fields
// for the ReadOne Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadOneInput(
	r *resource,
) bool {
	return r.ko.Spec.Name == nil

}

// newDescribeRequestPayload returns SDK-specific struct for the HTTP request
// payload of the Describe API call for the resource
func (rm *resourceManager) newDescribeRequestPayload(
	r *resource,
) (*svcsdk.DescribeDomainInput, error) {
	res := &svcsdk.DescribeDomainInput{}

	if r.ko.Spec.Name != nil {
		res.SetDomainName(*r.ko.Spec.Name)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer exit(err)
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}

	var resp *svcsdk.CreateDomainOutput
	_ = resp
	resp, err = rm.sdkapi.CreateDomainWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateDomain", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if resp.DomainStatus.ARN != nil {
		arn := ackv1alpha1.AWSResourceName(*resp.DomainStatus.ARN)
		ko.Status.ACKResourceMetadata.ARN = &arn
	}
	if resp.DomainStatus.AccessPolicies != nil {
		ko.Spec.AccessPolicies = resp.DomainStatus.AccessPolicies
	} else {
		ko.Spec.AccessPolicies = nil
	}
	if resp.DomainStatus.AdvancedOptions != nil {
		f2 := map[string]*string{}
		for f2key, f2valiter := range resp.DomainStatus.AdvancedOptions {
			var f2val string
			f2val = *f2valiter
			f2[f2key] = &f2val
		}
		ko.Spec.AdvancedOptions = f2
	} else {
		ko.Spec.AdvancedOptions = nil
	}
	if resp.DomainStatus.AdvancedSecurityOptions != nil {
		f3 := &svcapitypes.AdvancedSecurityOptionsInput{}
		if resp.DomainStatus.AdvancedSecurityOptions.Enabled != nil {
			f3.Enabled = resp.DomainStatus.AdvancedSecurityOptions.Enabled
		}
		if resp.DomainStatus.AdvancedSecurityOptions.InternalUserDatabaseEnabled != nil {
			f3.InternalUserDatabaseEnabled = resp.DomainStatus.AdvancedSecurityOptions.InternalUserDatabaseEnabled
		}
		if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions != nil {
			f3f2 := &svcapitypes.SAMLOptionsInput{}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Enabled != nil {
				f3f2.Enabled = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Enabled
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp != nil {
				f3f2f1 := &svcapitypes.SAMLIDp{}
				if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.EntityId != nil {
					f3f2f1.EntityID = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.EntityId
				}
				if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.MetadataContent != nil {
					f3f2f1.MetadataContent = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.Idp.MetadataContent
				}
				f3f2.IDp = f3f2f1
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.RolesKey != nil {
				f3f2.RolesKey = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.RolesKey
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes != nil {
				f3f2.SessionTimeoutMinutes = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes
			}
			if resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SubjectKey != nil {
				f3f2.SubjectKey = resp.DomainStatus.AdvancedSecurityOptions.SAMLOptions.SubjectKey
			}
			f3.SAMLOptions = f3f2
		}
		ko.Spec.AdvancedSecurityOptions = f3
	} else {
		ko.Spec.AdvancedSecurityOptions = nil
	}
	if resp.DomainStatus.AutoTuneOptions != nil {
		f4 := &svcapitypes.AutoTuneOptionsInput{}
		ko.Spec.AutoTuneOptions = f4
	} else {
		ko.Spec.AutoTuneOptions = nil
	}
	if resp.DomainStatus.ClusterConfig != nil {
		f5 := &svcapitypes.ClusterConfig{}
		if resp.DomainStatus.ClusterConfig.ColdStorageOptions != nil {
			f5f0 := &svcapitypes.ColdStorageOptions{}
			if resp.DomainStatus.ClusterConfig.ColdStorageOptions.Enabled != nil {
				f5f0.Enabled = resp.DomainStatus.ClusterConfig.ColdStorageOptions.Enabled
			}
			f5.ColdStorageOptions = f5f0
		}
		if resp.DomainStatus.ClusterConfig.DedicatedMasterCount != nil {
			f5.DedicatedMasterCount = resp.DomainStatus.ClusterConfig.DedicatedMasterCount
		}
		if resp.DomainStatus.ClusterConfig.DedicatedMasterEnabled != nil {
			f5.DedicatedMasterEnabled = resp.DomainStatus.ClusterConfig.DedicatedMasterEnabled
		}
		if resp.DomainStatus.ClusterConfig.DedicatedMasterType != nil {
			f5.DedicatedMasterType = resp.DomainStatus.ClusterConfig.DedicatedMasterType
		}
		if resp.DomainStatus.ClusterConfig.InstanceCount != nil {
			f5.InstanceCount = resp.DomainStatus.ClusterConfig.InstanceCount
		}
		if resp.DomainStatus.ClusterConfig.InstanceType != nil {
			f5.InstanceType = resp.DomainStatus.ClusterConfig.InstanceType
		}
		if resp.DomainStatus.ClusterConfig.WarmCount != nil {
			f5.WarmCount = resp.DomainStatus.ClusterConfig.WarmCount
		}
		if resp.DomainStatus.ClusterConfig.WarmEnabled != nil {
			f5.WarmEnabled = resp.DomainStatus.ClusterConfig.WarmEnabled
		}
		if resp.DomainStatus.ClusterConfig.WarmType != nil {
			f5.WarmType = resp.DomainStatus.ClusterConfig.WarmType
		}
		if resp.DomainStatus.ClusterConfig.ZoneAwarenessConfig != nil {
			f5f9 := &svcapitypes.ZoneAwarenessConfig{}
			if resp.DomainStatus.ClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount != nil {
				f5f9.AvailabilityZoneCount = resp.DomainStatus.ClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount
			}
			f5.ZoneAwarenessConfig = f5f9
		}
		if resp.DomainStatus.ClusterConfig.ZoneAwarenessEnabled != nil {
			f5.ZoneAwarenessEnabled = resp.DomainStatus.ClusterConfig.ZoneAwarenessEnabled
		}
		ko.Spec.ClusterConfig = f5
	} else {
		ko.Spec.ClusterConfig = nil
	}
	if resp.DomainStatus.CognitoOptions != nil {
		f6 := &svcapitypes.CognitoOptions{}
		if resp.DomainStatus.CognitoOptions.Enabled != nil {
			f6.Enabled = resp.DomainStatus.CognitoOptions.Enabled
		}
		if resp.DomainStatus.CognitoOptions.IdentityPoolId != nil {
			f6.IdentityPoolID = resp.DomainStatus.CognitoOptions.IdentityPoolId
		}
		if resp.DomainStatus.CognitoOptions.RoleArn != nil {
			f6.RoleARN = resp.DomainStatus.CognitoOptions.RoleArn
		}
		if resp.DomainStatus.CognitoOptions.UserPoolId != nil {
			f6.UserPoolID = resp.DomainStatus.CognitoOptions.UserPoolId
		}
		ko.Spec.CognitoOptions = f6
	} else {
		ko.Spec.CognitoOptions = nil
	}
	if resp.DomainStatus.Created != nil {
		ko.Status.Created = resp.DomainStatus.Created
	} else {
		ko.Status.Created = nil
	}
	if resp.DomainStatus.Deleted != nil {
		ko.Status.Deleted = resp.DomainStatus.Deleted
	} else {
		ko.Status.Deleted = nil
	}
	if resp.DomainStatus.DomainEndpointOptions != nil {
		f9 := &svcapitypes.DomainEndpointOptions{}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpoint != nil {
			f9.CustomEndpoint = resp.DomainStatus.DomainEndpointOptions.CustomEndpoint
		}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpointCertificateArn != nil {
			f9.CustomEndpointCertificateARN = resp.DomainStatus.DomainEndpointOptions.CustomEndpointCertificateArn
		}
		if resp.DomainStatus.DomainEndpointOptions.CustomEndpointEnabled != nil {
			f9.CustomEndpointEnabled = resp.DomainStatus.DomainEndpointOptions.CustomEndpointEnabled
		}
		if resp.DomainStatus.DomainEndpointOptions.EnforceHTTPS != nil {
			f9.EnforceHTTPS = resp.DomainStatus.DomainEndpointOptions.EnforceHTTPS
		}
		if resp.DomainStatus.DomainEndpointOptions.TLSSecurityPolicy != nil {
			f9.TLSSecurityPolicy = resp.DomainStatus.DomainEndpointOptions.TLSSecurityPolicy
		}
		ko.Spec.DomainEndpointOptions = f9
	} else {
		ko.Spec.DomainEndpointOptions = nil
	}
	if resp.DomainStatus.DomainId != nil {
		ko.Status.DomainID = resp.DomainStatus.DomainId
	} else {
		ko.Status.DomainID = nil
	}
	if resp.DomainStatus.DomainName != nil {
		ko.Spec.Name = resp.DomainStatus.DomainName
	} else {
		ko.Spec.Name = nil
	}
	if resp.DomainStatus.EBSOptions != nil {
		f12 := &svcapitypes.EBSOptions{}
		if resp.DomainStatus.EBSOptions.EBSEnabled != nil {
			f12.EBSEnabled = resp.DomainStatus.EBSOptions.EBSEnabled
		}
		if resp.DomainStatus.EBSOptions.Iops != nil {
			f12.IOPS = resp.DomainStatus.EBSOptions.Iops
		}
		if resp.DomainStatus.EBSOptions.VolumeSize != nil {
			f12.VolumeSize = resp.DomainStatus.EBSOptions.VolumeSize
		}
		if resp.DomainStatus.EBSOptions.VolumeType != nil {
			f12.VolumeType = resp.DomainStatus.EBSOptions.VolumeType
		}
		ko.Spec.EBSOptions = f12
	} else {
		ko.Spec.EBSOptions = nil
	}
	if resp.DomainStatus.EncryptionAtRestOptions != nil {
		f13 := &svcapitypes.EncryptionAtRestOptions{}
		if resp.DomainStatus.EncryptionAtRestOptions.Enabled != nil {
			f13.Enabled = resp.DomainStatus.EncryptionAtRestOptions.Enabled
		}
		if resp.DomainStatus.EncryptionAtRestOptions.KmsKeyId != nil {
			f13.KMSKeyID = resp.DomainStatus.EncryptionAtRestOptions.KmsKeyId
		}
		ko.Spec.EncryptionAtRestOptions = f13
	} else {
		ko.Spec.EncryptionAtRestOptions = nil
	}
	if resp.DomainStatus.Endpoint != nil {
		ko.Status.Endpoint = resp.DomainStatus.Endpoint
	} else {
		ko.Status.Endpoint = nil
	}
	if resp.DomainStatus.Endpoints != nil {
		f15 := map[string]*string{}
		for f15key, f15valiter := range resp.DomainStatus.Endpoints {
			var f15val string
			f15val = *f15valiter
			f15[f15key] = &f15val
		}
		ko.Status.Endpoints = f15
	} else {
		ko.Status.Endpoints = nil
	}
	if resp.DomainStatus.EngineVersion != nil {
		ko.Spec.EngineVersion = resp.DomainStatus.EngineVersion
	} else {
		ko.Spec.EngineVersion = nil
	}
	if resp.DomainStatus.LogPublishingOptions != nil {
		f17 := map[string]*svcapitypes.LogPublishingOption{}
		for f17key, f17valiter := range resp.DomainStatus.LogPublishingOptions {
			f17val := &svcapitypes.LogPublishingOption{}
			if f17valiter.CloudWatchLogsLogGroupArn != nil {
				f17val.CloudWatchLogsLogGroupARN = f17valiter.CloudWatchLogsLogGroupArn
			}
			if f17valiter.Enabled != nil {
				f17val.Enabled = f17valiter.Enabled
			}
			f17[f17key] = f17val
		}
		ko.Spec.LogPublishingOptions = f17
	} else {
		ko.Spec.LogPublishingOptions = nil
	}
	if resp.DomainStatus.NodeToNodeEncryptionOptions != nil {
		f18 := &svcapitypes.NodeToNodeEncryptionOptions{}
		if resp.DomainStatus.NodeToNodeEncryptionOptions.Enabled != nil {
			f18.Enabled = resp.DomainStatus.NodeToNodeEncryptionOptions.Enabled
		}
		ko.Spec.NodeToNodeEncryptionOptions = f18
	} else {
		ko.Spec.NodeToNodeEncryptionOptions = nil
	}
	if resp.DomainStatus.Processing != nil {
		ko.Status.Processing = resp.DomainStatus.Processing
	} else {
		ko.Status.Processing = nil
	}
	if resp.DomainStatus.ServiceSoftwareOptions != nil {
		f20 := &svcapitypes.ServiceSoftwareOptions{}
		if resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate != nil {
			f20.AutomatedUpdateDate = &metav1.Time{*resp.DomainStatus.ServiceSoftwareOptions.AutomatedUpdateDate}
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Cancellable != nil {
			f20.Cancellable = resp.DomainStatus.ServiceSoftwareOptions.Cancellable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion != nil {
			f20.CurrentVersion = resp.DomainStatus.ServiceSoftwareOptions.CurrentVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.Description != nil {
			f20.Description = resp.DomainStatus.ServiceSoftwareOptions.Description
		}
		if resp.DomainStatus.ServiceSoftwareOptions.NewVersion != nil {
			f20.NewVersion = resp.DomainStatus.ServiceSoftwareOptions.NewVersion
		}
		if resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment != nil {
			f20.OptionalDeployment = resp.DomainStatus.ServiceSoftwareOptions.OptionalDeployment
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable != nil {
			f20.UpdateAvailable = resp.DomainStatus.ServiceSoftwareOptions.UpdateAvailable
		}
		if resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus != nil {
			f20.UpdateStatus = resp.DomainStatus.ServiceSoftwareOptions.UpdateStatus
		}
		ko.Status.ServiceSoftwareOptions = f20
	} else {
		ko.Status.ServiceSoftwareOptions = nil
	}
	if resp.DomainStatus.SnapshotOptions != nil {
		f21 := &svcapitypes.SnapshotOptions{}
		if resp.DomainStatus.SnapshotOptions.AutomatedSnapshotStartHour != nil {
			f21.AutomatedSnapshotStartHour = resp.DomainStatus.SnapshotOptions.AutomatedSnapshotStartHour
		}
		ko.Status.SnapshotOptions = f21
	} else {
		ko.Status.SnapshotOptions = nil
	}
	if resp.DomainStatus.UpgradeProcessing != nil {
		ko.Status.UpgradeProcessing = resp.DomainStatus.UpgradeProcessing
	} else {
		ko.Status.UpgradeProcessing = nil
	}
	if resp.DomainStatus.VPCOptions != nil {
		f23 := &svcapitypes.VPCOptions{}
		if resp.DomainStatus.VPCOptions.SecurityGroupIds != nil {
			f23f1 := []*string{}
			for _, f23f1iter := range resp.DomainStatus.VPCOptions.SecurityGroupIds {
				var f23f1elem string
				f23f1elem = *f23f1iter
				f23f1 = append(f23f1, &f23f1elem)
			}
			f23.SecurityGroupIDs = f23f1
		}
		if resp.DomainStatus.VPCOptions.SubnetIds != nil {
			f23f2 := []*string{}
			for _, f23f2iter := range resp.DomainStatus.VPCOptions.SubnetIds {
				var f23f2elem string
				f23f2elem = *f23f2iter
				f23f2 = append(f23f2, &f23f2elem)
			}
			f23.SubnetIDs = f23f2
		}
		ko.Spec.VPCOptions = f23
	} else {
		ko.Spec.VPCOptions = nil
	}

	rm.setStatusDefaults(ko)
	if domainProcessing(&resource{ko}) {
		// Setting resource synced condition to false will trigger a requeue of
		// the resource. No need to return a requeue error here.
		ackcondition.SetSynced(&resource{ko}, corev1.ConditionFalse, nil, nil)
		return &resource{ko}, nil
	}

	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateDomainInput, error) {
	res := &svcsdk.CreateDomainInput{}

	if r.ko.Spec.AccessPolicies != nil {
		res.SetAccessPolicies(*r.ko.Spec.AccessPolicies)
	}
	if r.ko.Spec.AdvancedOptions != nil {
		f1 := map[string]*string{}
		for f1key, f1valiter := range r.ko.Spec.AdvancedOptions {
			var f1val string
			f1val = *f1valiter
			f1[f1key] = &f1val
		}
		res.SetAdvancedOptions(f1)
	}
	if r.ko.Spec.AdvancedSecurityOptions != nil {
		f2 := &svcsdk.AdvancedSecurityOptionsInput_{}
		if r.ko.Spec.AdvancedSecurityOptions.Enabled != nil {
			f2.SetEnabled(*r.ko.Spec.AdvancedSecurityOptions.Enabled)
		}
		if r.ko.Spec.AdvancedSecurityOptions.InternalUserDatabaseEnabled != nil {
			f2.SetInternalUserDatabaseEnabled(*r.ko.Spec.AdvancedSecurityOptions.InternalUserDatabaseEnabled)
		}
		if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions != nil {
			f2f2 := &svcsdk.MasterUserOptions{}
			if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserARN != nil {
				f2f2.SetMasterUserARN(*r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserARN)
			}
			if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserName != nil {
				f2f2.SetMasterUserName(*r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserName)
			}
			if r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserPassword != nil {
				tmpSecret, err := rm.rr.SecretValueFromReference(ctx, r.ko.Spec.AdvancedSecurityOptions.MasterUserOptions.MasterUserPassword)
				if err != nil {
					return nil, err
				}
				if tmpSecret != "" {
					f2f2.SetMasterUserPassword(tmpSecret)
				}
			}
			f2.SetMasterUserOptions(f2f2)
		}
		if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions != nil {
			f2f3 := &svcsdk.SAMLOptionsInput_{}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.Enabled != nil {
				f2f3.SetEnabled(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.Enabled)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp != nil {
				f2f3f1 := &svcsdk.SAMLIdp{}
				if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.EntityID != nil {
					f2f3f1.SetEntityId(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.EntityID)
				}
				if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.MetadataContent != nil {
					f2f3f1.SetMetadataContent(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.IDp.MetadataContent)
				}
				f2f3.SetIdp(f2f3f1)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterBackendRole != nil {
				f2f3.SetMasterBackendRole(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterBackendRole)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterUserName != nil {
				f2f3.SetMasterUserName(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.MasterUserName)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.RolesKey != nil {
				f2f3.SetRolesKey(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.RolesKey)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes != nil {
				f2f3.SetSessionTimeoutMinutes(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SessionTimeoutMinutes)
			}
			if r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SubjectKey != nil {
				f2f3.SetSubjectKey(*r.ko.Spec.AdvancedSecurityOptions.SAMLOptions.SubjectKey)
			}
			f2.SetSAMLOptions(f2f3)
		}
		res.SetAdvancedSecurityOptions(f2)
	}
	if r.ko.Spec.AutoTuneOptions != nil {
		f3 := &svcsdk.AutoTuneOptionsInput_{}
		if r.ko.Spec.AutoTuneOptions.DesiredState != nil {
			f3.SetDesiredState(*r.ko.Spec.AutoTuneOptions.DesiredState)
		}
		if r.ko.Spec.AutoTuneOptions.MaintenanceSchedules != nil {
			f3f1 := []*svcsdk.AutoTuneMaintenanceSchedule{}
			for _, f3f1iter := range r.ko.Spec.AutoTuneOptions.MaintenanceSchedules {
				f3f1elem := &svcsdk.AutoTuneMaintenanceSchedule{}
				if f3f1iter.CronExpressionForRecurrence != nil {
					f3f1elem.SetCronExpressionForRecurrence(*f3f1iter.CronExpressionForRecurrence)
				}
				if f3f1iter.Duration != nil {
					f3f1elemf1 := &svcsdk.Duration{}
					if f3f1iter.Duration.Unit != nil {
						f3f1elemf1.SetUnit(*f3f1iter.Duration.Unit)
					}
					if f3f1iter.Duration.Value != nil {
						f3f1elemf1.SetValue(*f3f1iter.Duration.Value)
					}
					f3f1elem.SetDuration(f3f1elemf1)
				}
				if f3f1iter.StartAt != nil {
					f3f1elem.SetStartAt(f3f1iter.StartAt.Time)
				}
				f3f1 = append(f3f1, f3f1elem)
			}
			f3.SetMaintenanceSchedules(f3f1)
		}
		res.SetAutoTuneOptions(f3)
	}
	if r.ko.Spec.ClusterConfig != nil {
		f4 := &svcsdk.ClusterConfig{}
		if r.ko.Spec.ClusterConfig.ColdStorageOptions != nil {
			f4f0 := &svcsdk.ColdStorageOptions{}
			if r.ko.Spec.ClusterConfig.ColdStorageOptions.Enabled != nil {
				f4f0.SetEnabled(*r.ko.Spec.ClusterConfig.ColdStorageOptions.Enabled)
			}
			f4.SetColdStorageOptions(f4f0)
		}
		if r.ko.Spec.ClusterConfig.DedicatedMasterCount != nil {
			f4.SetDedicatedMasterCount(*r.ko.Spec.ClusterConfig.DedicatedMasterCount)
		}
		if r.ko.Spec.ClusterConfig.DedicatedMasterEnabled != nil {
			f4.SetDedicatedMasterEnabled(*r.ko.Spec.ClusterConfig.DedicatedMasterEnabled)
		}
		if r.ko.Spec.ClusterConfig.DedicatedMasterType != nil {
			f4.SetDedicatedMasterType(*r.ko.Spec.ClusterConfig.DedicatedMasterType)
		}
		if r.ko.Spec.ClusterConfig.InstanceCount != nil {
			f4.SetInstanceCount(*r.ko.Spec.ClusterConfig.InstanceCount)
		}
		if r.ko.Spec.ClusterConfig.InstanceType != nil {
			f4.SetInstanceType(*r.ko.Spec.ClusterConfig.InstanceType)
		}
		if r.ko.Spec.ClusterConfig.WarmCount != nil {
			f4.SetWarmCount(*r.ko.Spec.ClusterConfig.WarmCount)
		}
		if r.ko.Spec.ClusterConfig.WarmEnabled != nil {
			f4.SetWarmEnabled(*r.ko.Spec.ClusterConfig.WarmEnabled)
		}
		if r.ko.Spec.ClusterConfig.WarmType != nil {
			f4.SetWarmType(*r.ko.Spec.ClusterConfig.WarmType)
		}
		if r.ko.Spec.ClusterConfig.ZoneAwarenessConfig != nil {
			f4f9 := &svcsdk.ZoneAwarenessConfig{}
			if r.ko.Spec.ClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount != nil {
				f4f9.SetAvailabilityZoneCount(*r.ko.Spec.ClusterConfig.ZoneAwarenessConfig.AvailabilityZoneCount)
			}
			f4.SetZoneAwarenessConfig(f4f9)
		}
		if r.ko.Spec.ClusterConfig.ZoneAwarenessEnabled != nil {
			f4.SetZoneAwarenessEnabled(*r.ko.Spec.ClusterConfig.ZoneAwarenessEnabled)
		}
		res.SetClusterConfig(f4)
	}
	if r.ko.Spec.CognitoOptions != nil {
		f5 := &svcsdk.CognitoOptions{}
		if r.ko.Spec.CognitoOptions.Enabled != nil {
			f5.SetEnabled(*r.ko.Spec.CognitoOptions.Enabled)
		}
		if r.ko.Spec.CognitoOptions.IdentityPoolID != nil {
			f5.SetIdentityPoolId(*r.ko.Spec.CognitoOptions.IdentityPoolID)
		}
		if r.ko.Spec.CognitoOptions.RoleARN != nil {
			f5.SetRoleArn(*r.ko.Spec.CognitoOptions.RoleARN)
		}
		if r.ko.Spec.CognitoOptions.UserPoolID != nil {
			f5.SetUserPoolId(*r.ko.Spec.CognitoOptions.UserPoolID)
		}
		res.SetCognitoOptions(f5)
	}
	if r.ko.Spec.DomainEndpointOptions != nil {
		f6 := &svcsdk.DomainEndpointOptions{}
		if r.ko.Spec.DomainEndpointOptions.CustomEndpoint != nil {
			f6.SetCustomEndpoint(*r.ko.Spec.DomainEndpointOptions.CustomEndpoint)
		}
		if r.ko.Spec.DomainEndpointOptions.CustomEndpointCertificateARN != nil {
			f6.SetCustomEndpointCertificateArn(*r.ko.Spec.DomainEndpointOptions.CustomEndpointCertificateARN)
		}
		if r.ko.Spec.DomainEndpointOptions.CustomEndpointEnabled != nil {
			f6.SetCustomEndpointEnabled(*r.ko.Spec.DomainEndpointOptions.CustomEndpointEnabled)
		}
		if r.ko.Spec.DomainEndpointOptions.EnforceHTTPS != nil {
			f6.SetEnforceHTTPS(*r.ko.Spec.DomainEndpointOptions.EnforceHTTPS)
		}
		if r.ko.Spec.DomainEndpointOptions.TLSSecurityPolicy != nil {
			f6.SetTLSSecurityPolicy(*r.ko.Spec.DomainEndpointOptions.TLSSecurityPolicy)
		}
		res.SetDomainEndpointOptions(f6)
	}
	if r.ko.Spec.Name != nil {
		res.SetDomainName(*r.ko.Spec.Name)
	}
	if r.ko.Spec.EBSOptions != nil {
		f8 := &svcsdk.EBSOptions{}
		if r.ko.Spec.EBSOptions.EBSEnabled != nil {
			f8.SetEBSEnabled(*r.ko.Spec.EBSOptions.EBSEnabled)
		}
		if r.ko.Spec.EBSOptions.IOPS != nil {
			f8.SetIops(*r.ko.Spec.EBSOptions.IOPS)
		}
		if r.ko.Spec.EBSOptions.VolumeSize != nil {
			f8.SetVolumeSize(*r.ko.Spec.EBSOptions.VolumeSize)
		}
		if r.ko.Spec.EBSOptions.VolumeType != nil {
			f8.SetVolumeType(*r.ko.Spec.EBSOptions.VolumeType)
		}
		res.SetEBSOptions(f8)
	}
	if r.ko.Spec.EncryptionAtRestOptions != nil {
		f9 := &svcsdk.EncryptionAtRestOptions{}
		if r.ko.Spec.EncryptionAtRestOptions.Enabled != nil {
			f9.SetEnabled(*r.ko.Spec.EncryptionAtRestOptions.Enabled)
		}
		if r.ko.Spec.EncryptionAtRestOptions.KMSKeyID != nil {
			f9.SetKmsKeyId(*r.ko.Spec.EncryptionAtRestOptions.KMSKeyID)
		}
		res.SetEncryptionAtRestOptions(f9)
	}
	if r.ko.Spec.EngineVersion != nil {
		res.SetEngineVersion(*r.ko.Spec.EngineVersion)
	}
	if r.ko.Spec.LogPublishingOptions != nil {
		f11 := map[string]*svcsdk.LogPublishingOption{}
		for f11key, f11valiter := range r.ko.Spec.LogPublishingOptions {
			f11val := &svcsdk.LogPublishingOption{}
			if f11valiter.CloudWatchLogsLogGroupARN != nil {
				f11val.SetCloudWatchLogsLogGroupArn(*f11valiter.CloudWatchLogsLogGroupARN)
			}
			if f11valiter.Enabled != nil {
				f11val.SetEnabled(*f11valiter.Enabled)
			}
			f11[f11key] = f11val
		}
		res.SetLogPublishingOptions(f11)
	}
	if r.ko.Spec.NodeToNodeEncryptionOptions != nil {
		f12 := &svcsdk.NodeToNodeEncryptionOptions{}
		if r.ko.Spec.NodeToNodeEncryptionOptions.Enabled != nil {
			f12.SetEnabled(*r.ko.Spec.NodeToNodeEncryptionOptions.Enabled)
		}
		res.SetNodeToNodeEncryptionOptions(f12)
	}
	if r.ko.Spec.Tags != nil {
		f13 := []*svcsdk.Tag{}
		for _, f13iter := range r.ko.Spec.Tags {
			f13elem := &svcsdk.Tag{}
			if f13iter.Key != nil {
				f13elem.SetKey(*f13iter.Key)
			}
			if f13iter.Value != nil {
				f13elem.SetValue(*f13iter.Value)
			}
			f13 = append(f13, f13elem)
		}
		res.SetTagList(f13)
	}
	if r.ko.Spec.VPCOptions != nil {
		f14 := &svcsdk.VPCOptions{}
		if r.ko.Spec.VPCOptions.SecurityGroupIDs != nil {
			f14f0 := []*string{}
			for _, f14f0iter := range r.ko.Spec.VPCOptions.SecurityGroupIDs {
				var f14f0elem string
				f14f0elem = *f14f0iter
				f14f0 = append(f14f0, &f14f0elem)
			}
			f14.SetSecurityGroupIds(f14f0)
		}
		if r.ko.Spec.VPCOptions.SubnetIDs != nil {
			f14f1 := []*string{}
			for _, f14f1iter := range r.ko.Spec.VPCOptions.SubnetIDs {
				var f14f1elem string
				f14f1elem = *f14f1iter
				f14f1 = append(f14f1, &f14f1elem)
			}
			f14.SetSubnetIds(f14f1)
		}
		res.SetVPCOptions(f14)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	// TODO(jaypipes): Figure this out...
	return nil, ackerr.NotImplemented
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer exit(err)
	if domainProcessing(r) {
		return r, requeueWaitWhileProcessing
	}

	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteDomainOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteDomainWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteDomain", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteDomainInput, error) {
	res := &svcsdk.DeleteDomainInput{}

	if r.ko.Spec.Name != nil {
		res.SetDomainName(*r.ko.Spec.Name)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.Domain,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}

	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	if syncCondition == nil && onSuccess {
		syncCondition = &ackv1alpha1.Condition{
			Type:   ackv1alpha1.ConditionTypeResourceSynced,
			Status: corev1.ConditionTrue,
		}
		ko.Status.Conditions = append(ko.Status.Conditions, syncCondition)
	}
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	if err == nil {
		return false
	}
	awsErr, ok := ackerr.AWSError(err)
	if !ok {
		return false
	}
	switch awsErr.Code() {
	case "ValidationException":
		return true
	default:
		return false
	}
}
