// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VpcEndpointSpec defines the desired state of VpcEndpoint.
//
// The connection endpoint for connecting to an Amazon OpenSearch Service domain
// through a proxy.
type VPCEndpointSpec struct {

	// The Amazon Resource Name (ARN) of the domain to create the endpoint for.
	//
	// Regex Pattern: `^arn:aws[a-z\-]*:[a-z]+:[a-z0-9\-]+:[0-9]+:domain\/[a-z0-9\-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	DomainARN *string                                  `json:"domainARN,omitempty"`
	DomainRef *ackv1alpha1.AWSResourceReferenceWrapper `json:"domainRef,omitempty"`
	// Options to specify the subnets and security groups for the endpoint.
	// +kubebuilder:validation:Required
	VPCOptions *VPCOptions `json:"vpcOptions"`
}

// VPCEndpointStatus defines the observed state of VPCEndpoint
type VPCEndpointStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The connection endpoint ID for connecting to the domain.
	//
	// Regex Pattern: `^[A-Za-z0-9\-\.]+$`
	// +kubebuilder:validation:Optional
	Endpoint *string `json:"endpoint,omitempty"`
	// The current status of the endpoint.
	// +kubebuilder:validation:Optional
	Status *string `json:"status,omitempty"`
	// The unique identifier of the endpoint.
	//
	// Regex Pattern: `^aos-[a-zA-Z0-9]*$`
	// +kubebuilder:validation:Optional
	VPCEndpointID *string `json:"vpcEndpointID,omitempty"`
	// The creator of the endpoint.
	//
	// Regex Pattern: `^[0-9]+$`
	// +kubebuilder:validation:Optional
	VPCEndpointOwner *string `json:"vpcEndpointOwner,omitempty"`
}

// VPCEndpoint is the Schema for the VPCEndpoints API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type VPCEndpoint struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VPCEndpointSpec   `json:"spec,omitempty"`
	Status            VPCEndpointStatus `json:"status,omitempty"`
}

// VPCEndpointList contains a list of VPCEndpoint
// +kubebuilder:object:root=true
type VPCEndpointList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCEndpoint `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VPCEndpoint{}, &VPCEndpointList{})
}
