// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VpcEndpointAccessSpec defines the desired state of VpcEndpointAccess.
type VPCEndpointAccessSpec struct {

	// The name of the OpenSearch Service domain to provide access to.
	//
	// Regex Pattern: `^[a-z][a-z0-9\-]+$`
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	DomainName *string                                  `json:"domainName,omitempty"`
	DomainRef  *ackv1alpha1.AWSResourceReferenceWrapper `json:"domainRef,omitempty"`
	// The AWS account or service authorized to access the domain through its
	// interface VPC endpoints.
	//
	// Either a 12-digit AWS account ID or an AWS service principal (for example
	// application.opensearchservice.amazonaws.com). The controller passes it to
	// AuthorizeVpcEndpointAccess and RevokeVpcEndpointAccess as the account or the
	// service argument accordingly.
	// +kubebuilder:validation:XValidation:rule="self == oldSelf",message="Value is immutable once set"
	// +kubebuilder:validation:Required
	Principal *string `json:"principal"`
	// Options that scope the authorization, such as the Regions it applies to.
	//
	// When left unset, the domain's own Region is authorized and reported back
	// here. Regions can be added or removed afterwards. Removing every Region
	// removes the authorization itself, so that is rejected: delete this resource
	// instead.
	ServiceOptions *ServiceOptions `json:"serviceOptions,omitempty"`
}

// VPCEndpointAccessStatus defines the observed state of VPCEndpointAccess
type VPCEndpointAccessStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
}

// VPCEndpointAccess is the Schema for the VPCEndpointAccesses API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
type VPCEndpointAccess struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              VPCEndpointAccessSpec   `json:"spec,omitempty"`
	Status            VPCEndpointAccessStatus `json:"status,omitempty"`
}

// VPCEndpointAccessList contains a list of VPCEndpointAccess
// +kubebuilder:object:root=true
type VPCEndpointAccessList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPCEndpointAccess `json:"items"`
}

func init() {
	SchemeBuilder.Register(&VPCEndpointAccess{}, &VPCEndpointAccessList{})
}
